import '../models/product_model.dart';

class global {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "Pav Bhaji",
      price: 70.0,
      image: "assets/images/food1.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "Parodha",
      price: 50.0,
      image: "assets/images/food2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Veg Biriyani",
      price: 90.0,
      image: "assets/images/food3.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 4,
      name: "Photo paneer tikka kabab",
      price: 80.0,
      image: "assets/images/food4.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "Pizz",
      price: 180.0,
      image: "assets/images/food5.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "barger",
      price: 85.0,
      image: "assets/images/food6.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "Apples",
      price: 120.0,
      image: "assets/images/fruit1.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "Mi Fruits",
      price: 29.0,
      image: "assets/images/fruit2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Unique Fruits",
      price: 40.0,
      image: "assets/images/fruit3.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "All Grocery",
      price: 100.0,
      image: "assets/images/gro1.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Mix Grocery",
      price: 120.0,
      image: "assets/images/gro2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Basic Grocery",
      price: 150.0,
      image: "assets/images/gro3.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Crude Grocery",
      price: 220.0,
      image: "assets/images/gro4.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "All Veges",
      price: 420.0,
      image: "assets/images/veg2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Mix Veges",
      price: 580.0,
      image: "assets/images/veg3.png",
      quantity: 0,
      like: "false",
    ),
  ];
}